name: Bob the Builder

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo "deb [arch=amd64] https://deb.troglobit.com/debian stable main" \
          	| sudo tee /etc/apt/sources.list.d/troglobit.list
          curl -sS https://deb.troglobit.com/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y update
          sudo apt-get -y install nemesis socat tshark
      - uses: actions/checkout@v2
      - name: Test
        run: |
          make check || (cat test/test-suite.log; false)
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: brist-test-${{ matrix.compiler }}
          path: test/*
